name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 15 * *'

jobs:

  black:
    name: Python Code Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@main"
      - name: Black Code Format Check
        uses: lgeiger/black-action@master
        with:
          args: ". --check --fast --diff"

  validate:
    name: Check hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@main"
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
